# This is a simple ECHO Server!!!

FROM ubuntu:xenial

MAINTAINER naveenmettu@gmail.com

RUN useradd -ms /bin/bash test

RUN echo "\n	\_>	Hello from image!!!	<_/	\n"

CMD "echo" "Hello from my container!!!"

USER test
